name: map_launcher_example
description: Demonstrates how to use the map_launcher plugin.
publish_to: "none"

version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  map_launcher:
    path: ../
  flutter_svg: ^0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
